### ISSUE TITLE
Redesign make new request process

### ISSUE THREAD

**Issue by TomSteinberg** [mysociety/alaveteli#1526]
- [x] **Select authority**
  - [x] Split select authority in to discrete pages (#1663)
  - [x] Move "Browse all or add a new one" to right column (https://github.com/mysociety/alaveteli/pull/1921)
  - [x] Reword to "find authority" (TBC)
  - [ ] Update URL to `/find_authority` (TBC)
  - [x] Minor text changes
  - [x] Add a "Make request" button to each body in search results to skip "Show authority" page (#2114)
- [x] **Show authority**
  - [x] Add logic to decide if we've just come from a search (#2051)
  - [x] Improve request listing section
  - [x] Re-add Follow/Other Info to wireframe
  - [x] Re-add search & filters to wireframe
  - [x] [Improve](#issuecomment-62695278) search and filter design
  - [x] Split some components into partials (#2032)
- [x] **Make a request**
  - [x] Improve typeahead search (#1666)
  - [x] Minor layout tweaks
  - [x] Minor rewording
- [x] **Preview your request**
  - [x] Minor layout tweaks
  - [x] Minor rewording
- [x] **Sign in/Sign up** (#1680)
- [x] **Check your email**
- [x] **Final Screen** (#1682)
- [ ] Update WDTK theme? (https://github.com/mysociety/whatdotheyknow-theme/pull/183)

---

Mammoth PR covering various areas: https://github.com/mysociety/alaveteli/pull/1681

---

**Deployment Tasks:**

- [ ] Check translations to see if we can reuse (#2050)

**Comment by zarino** [comment]
Regarding sharing: it's worth pointing out that my recent introduction of three "next steps" to the FixMyStreet design, used *dead simple* sharing links for Twitter and Facebook…

```html
<a href="https://twitter.com/intent/tweet?text=[% twitter_comment | uri %]&amp;url=[% share_url | uri %]&amp;related=fixmystreet,mysociety">
  <img src="/cobrands/fixmystreet/images/next-step-twitter.png" alt="Tweet it" width="120" height="37">
</a>
<a href="https://www.facebook.com/sharer/sharer.php?u=[% share_url | uri %]">
  <img src="/cobrands/fixmystreet/images/next-step-facebook.png" alt="Share on Facebook" width="120" height="37">
</a>
```

No javascript, no iframes. Simples.

**Comment by wrightmartin** [comment]
Thanks @zarino - very helpful

**Comment by garethrees** [comment]
```irc
[11:28:50]  <gareth>	 hmm, I prefer the original title actually ("ask for information")
[11:28:57]  <gareth>	 but we can change that later
[11:29:15]  <Martin>	 It was inconsistent I thought, all the way here we've called it request
[11:29:34]  <Martin>	 You could use a subtitle or something, becuase, yea, ask for information is a bit nicer
[11:29:47]  <gareth>	 Yeah. I like how "ask for information" is less technical
```
