### ISSUE TITLE
Set up Alaveteli Rwanda

### ISSUE THREAD

**Issue by paullenz** [mysociety/alaveteli#1950]
**See https://github.com/mysociety/sobanukirwa-theme/issues**

---

Set up a fairly vanilla instance of Alaveteli for Rwanda.  A few more details to be added to this ticket based upon feedback from Stephen Abbot, but points to note:

- [x] Initially in two languages, English and French
- [ ] 3 day required response time, with added note about the (shorter) exceptions to this rule (https://github.com/mysociety/sobanukirwa-theme/issues/6)
- [x] add to the template some additional text at the base of the form making it clear that there might be risks associated with using your real name and that you could use a pseudonym instead (https://github.com/mysociety/sobanukirwa-theme/issues/12)
- [x] replace every reference in the English site to "Freedom of Information"  with "Access to Information" (#1974)

**Comment by garethrees** [comment]
Closing this as it's up and tweaks are being handled in https://github.com/mysociety/sobanukirwa-theme/issues
