### ISSUE TITLE
Moderation / banning tools suggestions

### ISSUE THREAD

**Issue by skenaja** [mysociety/alaveteli#2691]
Some suggestions for improved moderation tools - feel free to break out into separate issues:

Use cases:
- admin user tracks down and bans sockpuppet accounts (eg for previously banned users)
- admin user tracks down human spammers (who can bypass captchas) - eg to find those registering accounts to add link spam to their user profile - and bans or deletes their accounts

*Store / search IP address to track activity on the site*

 - [ ] save IP addresses in the DB 
 - [ ] allow search by IP to view list of actions taken recently by that IP 
 - [ ] allow filtering of list by activity (Eg register, login, edit profile, send message to user), by userid
 - [ ] show IP(s) against on user profile (admin) - allow initiate 

*Ability to completely delete user accounts*
-  This would need to take into account any tracks, requests, outbound replies, annotations, profile photos.

**Comment by kingqueen3065** [comment]
I support this as a useful tool. Of particular note recently has been a number of attempts to sign up with false details and then automatically reply to the confirmation email with a spam, which hits the team@whatdotheyknow address - Helen has zapped a large number of these - and the accounts Alex has mentioned that are created solely to create links from our reputable site to a spammer's, to improve its page rank.

I am somewhat nervous of IP tracking based solutions because many of our users, being data rights savvy, may be understandably nervous of any ability to track users by IP. Our user profiles are great at the moment as they are so simple, they can comprise just a name and email address, and they have the minimum of extra information. I value this, it circumvents some privacy based concerns, and as an administrator I personally would rather not have the ability to track by IP.

**Comment by FOIMonkey** [comment]
There has been another recent uptick in the creation of accounts in order to post spam in the bio section. I've edited quite a few of these but the process is time consuming. It'd be good to have the option to easily delete the accounts entirely.

**Comment by RichardTaylor** [comment]
Would logging "IP address last logged in from" and making that available on a user admin page be a possible first step?

Perhaps if we did something like that we shouldn't hold it more than 30 days in line with the server log retention period?

On Wikipedia only 38 users have what they there call "CheckUser" privileges which let them see IP addresses for logged in users. https://en.wikipedia.org/wiki/Wikipedia:CheckUser  Alaveteli might want to follow that model and control access to such privacy sensitive information?

There is a current case on WhatDoTheyKnow where tools to identify people circumventing bans would be useful which has prompted this comment.

**Comment by RichardTaylor** [comment]
Just adding a +1

We've had another case on WDTK today where a public body and another user have raised suspicions that a user could be circumventing a ban and access to IP address records might have helped determine how likely that was.

**Comment by RichardTaylor** [comment]
Adding a +1 from the latest WhatDoTheyKnow catch up call. 

Could a hashed version of the IP address (last used and/or used for sign up) be stored enabling admins to see other connected accounts when there's a case of ban evasion / spam / other abuse of the site?

Privacy issues and compliance with our privacy policy is clearly a consideration.

**Comment by garethrees** [comment]
We could drop a cookie when someone tries to sign in to a banned account, and then prevent signups if that cookie exists.

* We'd have to publish the fact we use this cookie
* Private browsing or clearing cookies would get around the block

We could also look in to an [evercookie](https://samy.pl/evercookie/) or a browser fingerprint of some kind – both are a bit on the creepy side, so we'd want to be explicit about only doing this in extreme cases of misuse.

**Comment by garethrees** [comment]
> Are there any other social network sites that have a public invite tree like 
> lobsters? https://lobste.rs/u
> – https://twitter.com/teabass/status/1164145629913931776

Interesting idea:

<img width="919" alt="Screenshot 2019-08-21 at 18 29 29" src="https://user-images.githubusercontent.com/282788/63453930-a57f1c00-c441-11e9-9d42-07f84cc19824.png">

Its an invitation-only site though, so don't know how that could work for us.

<img width="863" alt="Screenshot 2019-08-21 at 18 30 25" src="https://user-images.githubusercontent.com/282788/63454024-e119e600-c441-11e9-94f4-4808ca392de3.png">

**Comment by RichardTaylor** [comment]
On WhatDoTheyKnow we've recently had a couple of users (and perhaps groups of users) persistently setting up new accounts to evade bans. 

I think IP based moderation tools are needed to tackle this kind of misuse.

**Comment by garethrees** [comment]
Some previous similar investigation got written up at https://github.com/mysociety/whatdotheyknow-theme/issues/365#issuecomment-279677892

**Comment by garethrees** [comment]
Quick sketch of auto-banning accounts that sign in to a previously banned account

```ruby
def sign_in
  session[:user_signins] << current_user.id

  if session[:user_signins].many?
    if User.where(id: session[:user_signins]).banned.any?
      ban_and_redirect(current_user) 
    end
  end
end
```

**Comment by garethrees** [comment]
Just dumping some notes from the last couple of days.

We can create a CSV of possible problem users by looking at whether they've made requests or comments to our target authorities. We can then manually take a look at the admin page for each and take necessary action.

```ruby
# IDENTIFYING BANNED USERS
# ------------------------------------------------------------------------------

require 'csv'

# TODO: Exclude pro users

# Has the user made a request or comment to a target body
def possibly_problematic?(user)
  body_ids = [
    525,
    1294
  ]

  user.info_requests.where(public_body_id: body_ids).any? ||
    user.comments.select { |c|
      body_ids.include?(c.info_request.public_body_id)
    }.any?
end

headers = %w[
  id
  name
  created_at
  banned?
  ban_text
  total_info_requests_count
  total_comments_count
]

users = User.where(created_at: Time.parse('2021-06-01')..Time.zone.now)

problem_users_csv = CSV.generate do |csv|
  csv << headers

  users.each do |user|
    next unless possibly_problematic?(user)
    csv << [
      user.id,
      user.name,
      user.created_at.strftime('%Y-%m-%d'),
      user.banned?,
      user.ban_text,
      user.info_requests.size,
      user.comments.size
    ]
  end
end

File.write('tmp/problem-users.csv', problem_users_csv)
```

We can also start our search with requests, looking for those with hidden content which may then reveal an unbanned user.

```ruby
# REQUESTS HIDDEN SINCE DECEMBER
# ------------------------------------------------------------------------------

require 'csv'

def has_hidden_content?(info_request)
  info_request.info_request_events.where(event_type: 'hide').any?
end

info_requests_to_target_bodies =
  InfoRequest.
    where(created_at: Time.parse('2021-12-01')..Time.zone.now).
    where(public_body_id: [525,1294])

headers = %w[
  id
  title
  created_at
  prominence
  has_hidden_content?
  user_name
  user_banned?
  user_ban_text
]

problem_requests_csv = CSV.generate do |csv|
  csv << headers

  info_requests_to_target_bodies.each do |ir|
    csv << [
      ir.id,
      ir.title,
      ir.created_at.strftime('%Y-%m-%d'),
      ir.prominence,
      has_hidden_content?(ir),
      ir.user.name,
      ir.user.banned?,
      ir.user.ban_text
    ]
  end
end

File.write('tmp/problem-requests.csv', problem_requests_csv)
```

**Comment by garethrees** [comment]
Given the above `problem-users.csv` we can import that to Google Sheets for our manual investigation.

Then we can filter on the "banned" column and extract a bunch of known bad user ids and [hide all their requests](https://github.com/mysociety/alaveteli/issues/3580#issuecomment-557102002) through the console.

![Screenshot 2022-02-23 at 15 45 42](https://user-images.githubusercontent.com/282788/155354533-422237be-dcfe-42b5-9579-240c7fb37b0f.png)

We can also use these IDs to do some wider-scale analysis.

```ruby
# Manually collect IDs from spreadsheet (this is just a small sample)
banned_user_ids = [242835, 244564, 242216, 244463, 243472, 242892, 241596,
                   244149, 244784, 245299, 245392, 247547, 243295, 247534,
                   247453, 245871, 244981, 247103, 244540]

banned_users = User.where(id: banned_user_ids).pluck(:email)

File.write('/tmp/banned-user-emails.txt', banned_users.join("\n"))
```

Find the IP addresses they used.

```sh
for email in $(cat /tmp/banned-user-emails.txt) ; do
  /root/get-ips-for-email 60 "$email" | cut -d: -f2 >> /tmp/banned-user-ips.txt
done
```

Find the origin country of the spam.

```sh
# Print lookup for each IP
for ip in $(cat /tmp/banned-user-ips.txt) ; do
  geoiplookup "$ip" | head -n 1 | cut -d: -f2 | tr -d " "
done

# Tally countries
$ for ip in $(cat /tmp/banned-user-ips.txt) ; do
  geoiplookup "$ip" | head -n 1 | cut -d: -f2 | tr -d " "
done | sort | uniq -c
#      4 GB,UnitedKingdom
#     31 PL,Poland
#     56 TW,Taiwan
```

**Comment by garethrees** [comment]
Thanks to the scripts from [yesterday](https://github.com/mysociety/alaveteli/issues/2691#issuecomment-1048849592), we can now look up problem users to identify signins to other accounts from the same IP:

Let’s say we identify a spam account signed up with `foo@example.com`. Let’s see what IPs that user has signed in with in the last 10 days:

```
# /root/get-ips-for-email 10 foo@example.com
./production.log.5.gz:1.2.3.4
./production.log.5.gz:1.2.3.4
./production.log.5.gz:1.2.3.4
./production.log.5.gz:4.3.2.1
```

Oh look,  6 other accounts using that IP address to sign in:

# /root/get-emails-for-ip 10 4.3.2.1
./production.log.5.gz:foo@example.com
./production.log.5.gz:bar@example.com
./production.log.5.gz:baz@example.com
./production.log.5.gz:foo@example.org
./production.log.5.gz:bar@example.org
./production.log.5.gz:baz@example.org
./production.log.5.gz:foo@example.net
```

We can now use those emails to check the admin interface page and programmatically [hide all their content](https://github.com/mysociety/alaveteli/issues/3580#issuecomment-1049996116).

**Comment by garethrees** [comment]
Just noting some extra bits:

Show me top sign in IPs

```
/root/get-signin-ips 1 | sort | uniq -c | sort -bgr | head
     18 37.REDACTED
     15 90.REDACTED
     10 REDACTED
     10 REDACTED
      9 REDACTED
    # snip
```

Show me top signin countries:

```
/root/get-signin-countries 1 | sort | uniq -c | sort -bgr | head
    653 GB
     35 US
     23 NL
     12 IN
     11 MY
      9 IP
      7 AU
      7 AE
      6 SE
      6 CA
```

**Comment by garethrees** [comment]
Closing as this is mostly resolved by https://github.com/mysociety/alaveteli/pull/6822.
