### ISSUE TITLE
Create template checklist of onboarding steps

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#2960]
Create a template checklist that we can paste in to issue 1 for new partner setups.

**Comment by crowbot** [comment]
Here's a starter: 

[Set up and get to know the site] (http://alaveteli.org/docs/getting_started/#step-one-get-a-working-uncustomised-version-running)
- [ ] Get an uncustomised version of the site running (mySociety)
- [ ] Create accounts on the site for partner team (partner)
- [ ] Set up admin accounts for the partner team (mySociety)
- [ ] Play with the site to see how it works as a user, as an administrator, and as a public authority (partner)
- [ ] Add some authorities the site using the admin interface (partner)

[Gather public authority information](http://alaveteli.org/docs/getting_started/#step-two-start-to-gather-data-about-public-authorities)
- [ ] Gather authority email addresses (partner) - [format template](https://docs.google.com/spreadsheets/d/13EIEydU9tufH53VMNHb_oU7vBBpR_QVk6K0s6jpW5Dw/edit?hl=en_US#gid=0) and [format help](http://alaveteli.org/docs/running/admin_manual/#creating-changing-and-uploading-public-authority-data).

[Customize the site](http://alaveteli.org/docs/getting_started/#step-three-customise-the-site)
- [ ] Create a logo for the site (partner) 
- [ ] Set up social media accounts for the site, tell mySociety what they are (partner)
- [ ] Configure social media accounts for the site (mySociety)
- [ ] Buy domain name (partner)
- [ ] Send information on how to point the DNS for this domain name to our servers (mySociety)
- [ ] Point DNS for domain name to our servers (partner)

[Translate the site]( http://alaveteli.org/docs/getting_started/#step-four-translate-everything)
- [ ] Translate the texts in transifex (partner)
- [ ] Write the help pages for the site (partner)

[Market the site](http://alaveteli.org/docs/getting_started/#step-six-market-the-website)
- [ ] Apply for an adwords grant (partner) 

[Maintain the site](http://alaveteli.org/docs/getting_started/#step-seven-maintain-the-website)

**Comment by JenMysoc** [comment]
I think we should also add in things like 

"Think about launch event (partner)
Consider press releases to relevant organisations (partner)
Think about audience and how to engage them in the platform before and after launch - for example; workshops with NGOs about how the site can help them get info for their work etc (partner)
Watch for interesting or high traffic requests/responses and consider how to market them (partner)

and of course: Ask if they will share google analytics data with us (mySociety)"

There are probably more :)

**Comment by garethrees** [comment]
Notes from the Onboarding Partners retreat session https://gist.github.com/garethrees/39216350fae352cfd834

**Comment by crowbot** [comment]
Closing this as we are piloting an initial checklist with the changes @JenMysoc suggests here with our Colombian partners.

**Comment by garethrees** [comment]
Just noting that this is now at https://github.com/mysociety/alaveteli/wiki/Checklist-for-setting-up-a-site-hosted-by-mySociety
