### ISSUE TITLE
Release 0.35

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5229]
Planned Ruby / OS support list https://gist.github.com/garethrees/ec3c403e1ea0744fb736381785e1e788

**Comment by lizconlan** [comment]
## Essentials

- [ ] [Drop support for Xenial](https://github.com/mysociety/alaveteli/pull/5318)
- [ ] [Fix BigDecimal deprecation warning](https://github.com/mysociety/alaveteli/pull/5314)
- [ ] [Add support for Ruby 2.6](https://github.com/mysociety/alaveteli/issues/5038)
- [ ] [Enable Pro features](https://github.com/mysociety/asktheeu-theme/issues/77)

## Nice to have

- [ ] [Open GeoIP-database-contrib isn't installable](https://github.com/mysociety/alaveteli/issues/5040)
- [ ] [Upgrade mail gem](https://github.com/mysociety/alaveteli/issues/4896)

**Comment by gbp** [comment]
Release in 293dde9c04badc493db295fb30462518bcffd0d0
