### ISSUE TITLE
Release 0.39

### ISSUE THREAD

**Issue by gbp** [mysociety/alaveteli#5830]
- [x] Upgrade mail gem #4896  
- [ ] ~Update to Rails 6 #5159~
- [x] Drop support for Ruby 2.3 #5222 
- [x] Drop support for Ruby 2.4 #5223 
- [ ] ~Add support for Ruby 2.7 #5440~
- [x] Add support for Debian Buster #5226
- [x] Extract WDTK Survey to Alaveteli https://github.com/mysociety/alaveteli/pull/6222

**Comment by garethrees** [comment]
@gbp any work left on this? Close if not 🙂
