### ISSUE TITLE
Add support checklist to /help/unhappy to help users understand how to challenge refusals

### ISSUE THREAD

**Issue by garethrees** [mysociety/alaveteli#5910]
On the **/help/unhappy** page we’ll introduce a new concept of a **checklist**. This will help users understand the pertinent parts of the act in an easier-to-digest format – [conceptual compression](https://m.signalvnoise.com/conceptual-compression-means-beginners-dont-need-to-know-sql-hallelujah/)!

The idea is that we help them check the refusal step by step, and progressively ask more detailed questions as we hone in on the advice we should give them.

When exemptions have been used, we’ll incorporate **specific advice** as well as the general advice for checking the request has been refused correctly.

In cases where the authority hasn’t refused correctly – say, they select “no, there wasn’t any use of exemptions” – we should highlight the **internal review link**, encouraging them to challenge.

We don’t want to prevent anyone from requesting an internal review though, so the option should always be available. This is about positively encouraging it if the authority clearly hasn’t done the right things.

As well as prompting an internal review, checklists should **filter the templates** that are shown by default on the new followup page (https://github.com/mysociety/alaveteli/issues/5911). I’m imagining that some JavaScript appends query params to the internal review link, or something like that.

We should consider how we make it easy for re-users to add checklists. They’ll be very site-specific so we probably can’t provide built-in examples, and most of our re-users aren’t particularly technical so lots of custom JavaScript won’t work.

The fallback option for re-users who want to offer better targeted guidance is to write the help page in HTML as before, where they can include links to the new followup page with hard-coded query params to filter the templates.

We’ll also want to incorporate some **case studies** on this page, to show examples of successful challenges. The case studies will be published on our blog, so this will be more about nicely presenting a snippet to provide some social proof that challenging is okay to do and can be successful.

We’ll include the **fallback options** – make a new request, write to your MP, etc – in plain text as before.

Users are also directed to **/help/unhappy** when their request is **late**, or the authority says they **don’t hold the information**. Hopefully we’ll be able to treat these in a similar way to a request being refused – provide a **checklist** and then present relevant **templates**. I’ve marked them as “bonuses” because the core goal of this project is to challenge _refusals_. We already have a reasonable workflow for late requests, and it’s difficult to do anything when an authority says they don’t have the information you’ve asked for.

![Screenshot 2020-10-05 at 12 29 58](https://user-images.githubusercontent.com/282788/95074448-80fa0800-0706-11eb-9e3a-5e53d5f1ec78.png)

The **general advice** on **/help/unhappy** will include a question along the lines of “They did cite an exemption?” Given an affirmative answer we’ll need to ask which exemptions were cited to be able to better target the advice we give.

Selecting exemptions will reveal specific **checklists** and **guidance** for those exemptions, and ultimately result in more filters being added to narrow down the **templates** shown on the **new followup** page.

We can pre-select any exemptions we’ve **automatically identified** (https://github.com/mysociety/alaveteli/issues/5909) in the request – we should make it clear that we’ve done this – but we’ll need to allow the user to make the final call on which to select since our identification won’t be perfect.

Even without the checklists, this page is pretty long. We might want to link to new exemption-specific **help pages** (e.g. `/help/refused/section_22`) from the specific exemption guidance if it turns out we have lots to say about them. If we do this we’ll need to think about persisting the state of checklists so that users don’t lose all their work as they flip between **/help/unhappy** and the exemption-specific help.

![Screenshot 2020-10-05 at 12 33 25](https://user-images.githubusercontent.com/282788/95074753-fb2a8c80-0706-11eb-88e6-843127871829.png)

Again we’ll need to consider how re-users can add **specific guidance** without needing lots of custom development effort. 

---

- [x] Parse refusal advice configuration and generate HTML  https://github.com/mysociety/alaveteli/issues/5937
- [ ] Decide what the refusal advice should present when we don't have JavaScript enabled  https://github.com/mysociety/alaveteli/issues/5938
- [x] Build refusals advice Q&A interface https://github.com/mysociety/alaveteli/issues/5939
- [x] Handling of pre-identified exemptions OR asking the user which ones have been used 
 https://github.com/mysociety/alaveteli/issues/5940

**Comment by zarino** [comment]
@garethrees and I assume, even in the case where there’s only one question in the request, and the authority has cited _only one_ exemption in their refusal, it might still be the case that the authority has done multiple things wrong / made multiple mistakes in coming to that decision, so the user has multiple grounds on which to challenge the refusal? (And therefore multiple response templates to choose from.)

**Comment by garethrees** [comment]
> it might still be the case that the authority has done multiple things wrong / made multiple mistakes

Yep!

e.g. they might essentially just say "No!" without:

1. Confirming or denying whether they hold the information
2. Providing a specific exemption as to why they can refuse

**Comment by zarino** [comment]
So, looking at @MyfanwyNixon’s draft questions/answers in #5912, here are a few notes for next time I pick this up:

* The aim of the questions is to identify response templates, or other specific support materials, we can show to the user, to help them challenge the refusal.
* Questions sometimes have supporting text, which isn’t part of the question itself, but helps you interpret the question.
* Once you give an answer to a question, you might uncover:
   * One or more actions to take – typically just one, and it’s either requesting an internal review, or sending a regular reply to better understand the reasons for refusal.
      * The actions usually need to be accompanied by some text, explaining why the action is viable, and what to mention while doing it.
      * If we’re telling them to request an internal review, or ask a question, then we will probably have a template snippet they can use.
   * One or more follow-up questions for the user to answer
   * A "dead end" – ie: the chain of answers results in neither an action to take, nor more questions to ask
* There might be multiple, unrelated, top-level questions at the start – especially if we detect multiple exemptions being used in the refusal message, which means multiple different question trees to complete.
* The "chains" of nested questions and answers could potentially get quite deep. But I think three steps (top level > child > grandchild) is the deepest I’ve seen in Myf’s draft content so far.
* There might be multiple "grounds" for challenging a refusal, so we really want people to answer _all_ of the questions until there are no more left to answer, rather than jumping out to do the first action they encounter.

A few thoughts about presentation:

* I’m not sure there’s much value in indenting the different levels of question. It’ll add visual complexity, and I don’t think users gain much value from seeing which questions led to which other questions. Look at displaying "child" questions immediately after their parent, at the same level, to keep it simple?
* We’ll need a single collection of "actions" at the end, rather than presenting them inline after the answer that triggered them. This might mean that we end up with a "Request an internal review" prompt at the end, with multiple "grounds" for review within it, collected from various points throughout the question tree.
* Users should be able to change their answers (ie: switch from yes to no, or no to yes) and everything should work, even if that means resetting whole chunks of the tree further down from that point.

**Comment by garethrees** [comment]
> We’ll need a single collection of "actions" at the end, rather than presenting them inline after the answer that triggered them. This might mean that we end up with a "Request an internal review" prompt at the end, with multiple "grounds" for review within it, collected from various points throughout the question tree.

This sounds really effective! Where we think there are clear grounds we can present them in a nice, clear, encouraging way.

When we're less clear, we can tone down the "actions collection" with whatever advice we can compile for what to do next.

![2020-10-15-questions-actions-collection](https://user-images.githubusercontent.com/282788/96100883-c1a70d80-0ecc-11eb-81f6-4c8d022d93dd.jpg)

**Comment by garethrees** [comment]
I've spiked out (https://github.com/mysociety/alaveteli/pull/5923) the rendering of questions defined in a data structure based on a simplistic overview of the draft Q&As in https://github.com/mysociety/alaveteli/issues/5912. Would be good to get your input on that @zarino to see if it maps with what you were thinking from the frontend POV.

**Comment by garethrees** [comment]
@zarino has put together [an amazing  prototype](https://github.com/mysociety/foi-refusals-prototype) of this so that we can get a feel for how it works in practice.

![Screenshot 2020-10-19 at 12 03 25](https://user-images.githubusercontent.com/282788/96443765-08ff0800-1205-11eb-9feb-f65d14252408.png)


I'm a fan of the general direction.

A few points to think about that we discussed on standup this morning:

* We're going to add the entire section 12 advice so that we get a good sense of any edge cases.
* It doesn't feel quite right to have multiple individual actions presented at the bottom. We want to try grouping advice into collections (grounds for appeal, questions to ask, etc).
* It's a bit confusing for new items to just appear, so we'll experiment with some transitions.

I'm also wondering about a couple of other things now I've had chance to look at it in more detail.

* This obviously needs JS to work. What do we do if JS disabled? Is there a way we can render everything out?
* There's potentially a lot of information to remember between here and the next page where the user actually writes their followup message. We'll have selected appropriate templates, but there'll almost certainly be info that you'll want to refer back to. We might want to preserve the state of the questionnaire and the text in the followup form so that you can go back and forth freely.
* Alternatively we could re-render the selected actions onto the followup form page itself.

**Comment by RichardTaylor** [comment]
Brilliant prototype. 

It looks tantalisingly close to drafting a reply (which I realise is probably a few steps further than the scope of this project!)

Could clicking "Send a reply" lead to a reply form with the advice still visible to refer to?

If I was faced with that I might copy and paste the advice before clicking the "Send a reply" button so I could quote the advice in a reply. 

Is the assumption the conclusion will be a single piece of advice or might there be a series of suggestions?

**Comment by garethrees** [comment]
> Brilliant prototype.

Thanks! All @zarino's hard work!

> Could clicking "Send a reply" lead to a reply form with the advice still visible to refer to?

That's what I was thinking with:

> * Alternatively we could re-render the selected actions onto the followup form page itself.
>
> – https://github.com/mysociety/alaveteli/issues/5910#issuecomment-712080328

> It looks tantalisingly close to drafting a reply (which I realise is probably a few steps further than the scope of this project!)
> …
> If I was faced with that I might copy and paste the advice before clicking the "Send a reply" button so I could quote the advice in a reply.

The idea is that this at least leads to a targeted set of templates (https://github.com/mysociety/alaveteli/issues/5911) that the user can add to the reply – which is not _too_ far off this. I'm hoping that this will make it as easy to created a slightly more tailored reply.

> Is the assumption the conclusion will be a single piece of advice or might there be a series of suggestions?

More towards the latter.

We'll always show the link to the followup form, but we'll likely emphasise it more when there are reasons we think the user should follow up, with the highest level of emphasis being a recommendation to request an internal review.

**Comment by zarino** [comment]
@garethrees – Aside from asking for an internal review, or sending a reply to seek clarification, are there any other “actions” that we want to present to people in this interface? (They might be actions that are always presented, regardless of responses to the checklist questions?)

**Comment by garethrees** [comment]
Yep:

> We’ll include the **fallback options** – make a new request, write to your MP, etc – in plain text as before.
>
> – https://github.com/mysociety/alaveteli/issues/5910#issue-714760653

We don't want to lose too much of the guidance already on [`/help/unhappy`](https://www.whatdotheyknow.com/help/unhappy). I don't have any particular opinions about how we do this, but as a starter idea we could:

1. Extract [refer to ICO](https://www.whatdotheyknow.com/help/unhappy#refer-to-ico) to it's own help page and link to it to really shorten the text on this page.
2. Clean up [other means](https://www.whatdotheyknow.com/help/unhappy#other_means) with some `<details>` tags.

**Comment by garethrees** [comment]
I should clarify. I think we'll have two "button" options on the golden path:

1. Request an internal review
2. Write a followup (or, Write a reply – same meaning)

We'll then have a list of plain text and links when one of the above isn't the correct course of action (the **fallback options**).

**Comment by zarino** [comment]
@garethrees here’s an updated prototype. Would be interested to get your thoughts:

https://mysociety.github.io/foi-refusals-prototype/section-12

Excuse the janky sliding animations for the suggestions at the bottom – doesn’t seem worth making them smooth just for a prototype.

My initial thoughts:

1. Grouping all the "grounds" for an internal review, or all the questions to ask in a reply, feels useful, and quite natural.
2. But I feel like the different paragraphs in those coloured boxes need to more clearly look like separate statements, rather than one big long piece of text.
3. Most worryingly, I feel like the "live" unfolding of the suggestions at the end might distract people away from completing the checklist. I wonder whether the results should only be generated once you’ve answered all the applicable questions?

**Comment by garethrees** [comment]
@zarino will look at this properly tomorrow morning. In general it's looking pretty great 🙇 .

**Comment by garethrees** [comment]
This is looking _so_ good 👌 

## Specific Questions

> Grouping all the "grounds" for an internal review, or all the questions to ask in a reply, feels useful, and quite natural.
> …
> But I feel like the different paragraphs in those coloured boxes need to more clearly look like separate statements, rather than one big long piece of text.

Yeah, I really like this direction. Did you try a bulleted/numbered list for each point? Might be a way to make it clearer that each point is a card in your hand.

> Most worryingly, I feel like the "live" unfolding of suggestions at the end might distract people away from completing the checklist. I wonder whether the results should only be generated once you’ve answered all the applicable questions?

Well, I agree in some ways, but I don't think we want to _force_ people to complete the entire form (or, any of it!) if they don't want to (they may already know full well that they have a case for review and know how to press the authority on the issues). This is definitely a _support_ system rather than a requirement.

I assume we can figure out if there are more questions to answer, so perhaps we can essentially say that, while still allowing people to go through to the next step if they're happy to do so.

I don't fully like this idea, but as a starter:

1. When there are incomplete questions, we mute the button style and give some sort of message to complete the form

![Screenshot 2020-10-21 at 09 49 52](https://user-images.githubusercontent.com/282788/96696563-cfeca200-1382-11eb-80e8-f1f5850eba2b.png)

2. When there are complete questions, we increase prominence of the button

![Screenshot 2020-10-21 at 09 50 33](https://user-images.githubusercontent.com/282788/96696635-e561cc00-1382-11eb-8aac-893d79607cd7.png)

Some other ideas to explore:

* We could pop up a dialog with the "incomplete questions" message, but that feels annoying.
* Maybe there's some sort of progress bar analogy that we could use?
* Could we make unanswered questions bold, and then reduce font weight when they get answered?

![Screenshot 2020-10-21 at 10 02 29](https://user-images.githubusercontent.com/282788/96698077-99b02200-1384-11eb-9e86-2b7e637a0ce3.png)

I am wondering whether the suggestions panel could be a sidebar element so that it feels like you're creating a shopping list, or adding items to your basket. 

## General Thoughts

It would be worth a test of what we do when we haven't automatically identified any exemptions. How do we get the user to the correct set of questions? It's also pretty common for authorities to refuse with multiple exemptions (either for the whole request, or different exemptions for different parts of the request).

I really like the new "Next steps" panel, but I think we should have two distinct groupings. I think we want "Next steps" to have a little more weight than "Other routes", since our primary goal is getting _this_ request answered successfully. The other routes are less ideal, but can be used if you don't have good grounds for appeal or you've exhausted that process.

![Screenshot 2020-10-21 at 10 09 47](https://user-images.githubusercontent.com/282788/96698924-936e7580-1385-11eb-808d-0f67c9133f64.png)

We haven't really tackled what we do when JS is disabled. Perhaps we just use the current text content as a fallback?

**Comment by zarino** [comment]
Useful feedback, thanks @garethrees. I’ll work through it in a bit. But while I’m thinking about it:

> We haven't really tackled what we do when JS is disabled. Perhaps we just use the current text content as a fallback?

There’s nothing about this that couldn’t be done entirely server-side. I’m imagining a submit button after each radio button (which gets hidden if JS runs), that submits all your radio selections so far, and then returns an updated page with the next question(s) revealed for you to fill in / final suggestions revealed for you to start your (templated) responses. Might be a lot of work to implement though…

**Comment by skenaja** [comment]
> It would be worth a test of what we do when we haven't automatically identified any exemptions. How do we get the user to the correct set of questions? 

Would something like this work? The start button takes you along the journey of being asked the relevant questions. I'm thinking along the lines of [this pattern](https://design-system.service.gov.uk/patterns/start-pages/). Also, this would make the the refusal tool a useful resource to people who haven't made requests via WDTK. 

Similar text/call to action on `/help/unhappy/request_name`, and possibly also on `/request/<id>/followups/new?internal_review=1#followup`

![image](https://user-images.githubusercontent.com/510285/96717929-2f58ab00-139f-11eb-94d0-57fcaea579e4.png)

**Comment by zarino** [comment]
@garethrees How about this for an alternative that presents one question at a time, and displays some idea of progress?

https://mysociety.github.io/foi-refusals-prototype/section-12-chatbot

![chatbot](https://user-images.githubusercontent.com/739624/96746882-8cfcef80-13bf-11eb-965b-f8f15f4f09b9.png)

(Apologies – I’m running out of time on this, so this new demo is very "on rails" – it only covers the first 4 questions of Section 12, and you can only answer "yes" to all of them!)

A few thoughts:

* The number of "remaining" questions, and the progress bar, can potentially go both up and down, as you enter and then clear different "branches" of the decision tree. I don’t think this is too big an issue, but very observant people might find it odd.
* Unlike the previous prototype, this one requires you to click a button to submit your answer at each stage. We _could_ make it automatic, but since we’re no longer letting people go back and edit their past questions, it felt a bit unkind to whisk them onto the next question without at least getting confirmation that they are happy with their choice. Sometimes people misclick. … Maybe we need a way to go back and edit your previous answers :-/
* Weirdly this is one of those cases where I feel like a delay (either artificial, or because of ajax stuff sending the answer and receiving the next question) could actually improve the experience. It feels a bit "fake" when you get a UI update immediately after pressing the submit button.

**Comment by garethrees** [comment]
This is really interesting. It certainly feels more coherent – new things appear in a much more controlled manner, the flow through a batch of questions one at a time feels logical, and there's a clear "result" at the end.

It does have some downsides though. You can't see past answers, so you can't see an overall picture. If you wanted to, you could complete [the original](https://mysociety.github.io/foi-refusals-prototype/section-12) questionnaire and print it out and hand it to your editor to show them how we came to the conclusion that they should appeal, for example.

I'm also wondering about implementation. I was hoping to avoid complex server-side stuff due to the way help pages are customised per install.

Maybe its time for us all to hop on a call and just have a general chat through our options?

**Comment by zarino** [comment]
@garethrees yes, a call sounds good!

**Comment by garethrees** [comment]
Based on our discussion today, I've extracted some more specific issues and linked them from [the main issue body](https://github.com/mysociety/alaveteli/issues/5910#issue-714760653).

**Comment by garethrees** [comment]
Going to consider the core of this done  as of https://github.com/mysociety/alaveteli/pull/5948and further, specific work can be tracked in new issues.
